/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdottiIndexRouteImport } from './routes/prodotti.index'
import { Route as ProdottiSlugRouteImport } from './routes/prodotti.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdottiIndexRoute = ProdottiIndexRouteImport.update({
  id: '/prodotti/',
  path: '/prodotti/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdottiSlugRoute = ProdottiSlugRouteImport.update({
  id: '/prodotti/$slug',
  path: '/prodotti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prodotti/$slug': typeof ProdottiSlugRoute
  '/prodotti/': typeof ProdottiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prodotti/$slug': typeof ProdottiSlugRoute
  '/prodotti': typeof ProdottiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prodotti/$slug': typeof ProdottiSlugRoute
  '/prodotti/': typeof ProdottiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prodotti/$slug' | '/prodotti/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prodotti/$slug' | '/prodotti'
  id: '__root__' | '/' | '/prodotti/$slug' | '/prodotti/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProdottiSlugRoute: typeof ProdottiSlugRoute
  ProdottiIndexRoute: typeof ProdottiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prodotti/': {
      id: '/prodotti/'
      path: '/prodotti'
      fullPath: '/prodotti/'
      preLoaderRoute: typeof ProdottiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prodotti/$slug': {
      id: '/prodotti/$slug'
      path: '/prodotti/$slug'
      fullPath: '/prodotti/$slug'
      preLoaderRoute: typeof ProdottiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProdottiSlugRoute: ProdottiSlugRoute,
  ProdottiIndexRoute: ProdottiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
